syntax = "proto3";

package executor;

// Common request structure for both JS and Python
message ExecutorRequest {
    string opData = 1;
    string g = 2; // global context about organisation, user, region, location
    string additional_params = 3; // will have document definition if required, and view 
    string code = 4;
}

// Response message containing the execution result
message ExecutorResponse {
    string result = 1;
}

// Code execution service with language-specific RPCs
service ExecutorService {
    rpc xrunJavascript (ExecutorRequest) returns (ExecutorResponse);
    rpc xrunPython (ExecutorRequest) returns (ExecutorResponse);
}