// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobuf/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAuthParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Organisation  string                 `protobuf:"bytes,2,opt,name=organisation,proto3" json:"organisation,omitempty"`
	UserType      string                 `protobuf:"bytes,3,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthParams) Reset() {
	*x = UserAuthParams{}
	mi := &file_protobuf_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthParams) ProtoMessage() {}

func (x *UserAuthParams) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthParams.ProtoReflect.Descriptor instead.
func (*UserAuthParams) Descriptor() ([]byte, []int) {
	return file_protobuf_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuthParams) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *UserAuthParams) GetOrganisation() string {
	if x != nil {
		return x.Organisation
	}
	return ""
}

func (x *UserAuthParams) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type UserApiKeyParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Organisation  string                 `protobuf:"bytes,2,opt,name=organisation,proto3" json:"organisation,omitempty"`
	UserType      string                 `protobuf:"bytes,3,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserApiKeyParams) Reset() {
	*x = UserApiKeyParams{}
	mi := &file_protobuf_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserApiKeyParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserApiKeyParams) ProtoMessage() {}

func (x *UserApiKeyParams) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserApiKeyParams.ProtoReflect.Descriptor instead.
func (*UserApiKeyParams) Descriptor() ([]byte, []int) {
	return file_protobuf_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UserApiKeyParams) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UserApiKeyParams) GetOrganisation() string {
	if x != nil {
		return x.Organisation
	}
	return ""
}

func (x *UserApiKeyParams) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type UserAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthResponse) Reset() {
	*x = UserAuthResponse{}
	mi := &file_protobuf_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthResponse) ProtoMessage() {}

func (x *UserAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthResponse.ProtoReflect.Descriptor instead.
func (*UserAuthResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserAuthResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UserAuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protobuf_auth_auth_proto protoreflect.FileDescriptor

const file_protobuf_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/auth/auth.proto\x12\bUserAuth\"p\n" +
	"\x0eUserAuthParams\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\"\n" +
	"\forganisation\x18\x02 \x01(\tR\forganisation\x12\x1b\n" +
	"\tuser_type\x18\x03 \x01(\tR\buserType\"l\n" +
	"\x10UserApiKeyParams\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\"\n" +
	"\forganisation\x18\x02 \x01(\tR\forganisation\x12\x1b\n" +
	"\tuser_type\x18\x03 \x01(\tR\buserType\"V\n" +
	"\x10UserAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xa9\x01\n" +
	"\bUserAuth\x12N\n" +
	"\x14GetUserFromAuthToken\x12\x18.UserAuth.UserAuthParams\x1a\x1a.UserAuth.UserAuthResponse\"\x00\x12M\n" +
	"\x11GetUserFromApiKey\x12\x1a.UserAuth.UserApiKeyParams\x1a\x1a.UserAuth.UserAuthResponse\"\x00B\tZ\ago/authb\x06proto3"

var (
	file_protobuf_auth_auth_proto_rawDescOnce sync.Once
	file_protobuf_auth_auth_proto_rawDescData []byte
)

func file_protobuf_auth_auth_proto_rawDescGZIP() []byte {
	file_protobuf_auth_auth_proto_rawDescOnce.Do(func() {
		file_protobuf_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_auth_auth_proto_rawDesc), len(file_protobuf_auth_auth_proto_rawDesc)))
	})
	return file_protobuf_auth_auth_proto_rawDescData
}

var file_protobuf_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_auth_auth_proto_goTypes = []any{
	(*UserAuthParams)(nil),   // 0: UserAuth.UserAuthParams
	(*UserApiKeyParams)(nil), // 1: UserAuth.UserApiKeyParams
	(*UserAuthResponse)(nil), // 2: UserAuth.UserAuthResponse
}
var file_protobuf_auth_auth_proto_depIdxs = []int32{
	0, // 0: UserAuth.UserAuth.GetUserFromAuthToken:input_type -> UserAuth.UserAuthParams
	1, // 1: UserAuth.UserAuth.GetUserFromApiKey:input_type -> UserAuth.UserApiKeyParams
	2, // 2: UserAuth.UserAuth.GetUserFromAuthToken:output_type -> UserAuth.UserAuthResponse
	2, // 3: UserAuth.UserAuth.GetUserFromApiKey:output_type -> UserAuth.UserAuthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_auth_auth_proto_init() }
func file_protobuf_auth_auth_proto_init() {
	if File_protobuf_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_auth_auth_proto_rawDesc), len(file_protobuf_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_auth_auth_proto_goTypes,
		DependencyIndexes: file_protobuf_auth_auth_proto_depIdxs,
		MessageInfos:      file_protobuf_auth_auth_proto_msgTypes,
	}.Build()
	File_protobuf_auth_auth_proto = out.File
	file_protobuf_auth_auth_proto_goTypes = nil
	file_protobuf_auth_auth_proto_depIdxs = nil
}
