on:
  push:
    branches:
      - test
name: Build

jobs:
  BuildPython:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Install 
        run: |
          python scripts/python/generate_lib.py 
          python scripts/python/setup.py bdist_wheel

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: python
          path: dist/*.whl
        


