on:
  push:
    branches:
      - bugfix/grpc-generate-lib
name: Build

jobs:
  BuildPython:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.1.5
      # Get the last two files in the dist directory
      LAST_TWO_FILES: $(ls -t dist/* | head -n 2)
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10-dev"

      - name: Install Dependencies
        run: |
          pip install grpcio-tools setuptools wheel

      - name: Generate Library
        run: |
          python scripts/python/generate_lib.py ${{ env.VERSION }}

      - name: Check and Upload to PyPI
        run: |
          pip install twine

          # Check the last two files
          twine check ${{env.LAST_TWO_FILES}}

          # Upload the last two files
          twine upload ${{env.LAST_TWO_FILES}} --username __token__ --password ${{ secrets.PYPI_API_KEY }}

      - name: Release (Optional)
        run: echo "Release to PyPI is handled automatically with twine upload."
