on:
  push:
    branches:
      - develop
name: Build

jobs:
  BuildPython:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10-dev' 
      
      - name: Install 
        run: |
          pip3 install grpcio-tools
          pip3 install wheel
          PROTO_BUF_LIB_VERSION=${{env.VERSION}} python scripts/python/generate_lib.py 
          PROTO_BUF_LIB_VERSION=${{env.VERSION}} python scripts/python/setup.py bdist_wheel


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: python
          path: dist/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          name: V${{env.VERSION}}
          tag_name: V${{env.VERSION}}
          token: ${{ secrets.GRPC_RELEASE_TOKEN }}
        


